config/routes.rb
Tubez::Application.routes.draw do
 root :to => 'home#index'
 get '/videos/new' => 'videos#new'
 post '/videos/new' => 'videos#search'
 get '/videos' => 'videos#index'
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  url        :string(255)
#  views      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Video < ActiveRecord::Base
  attr_accessible :title, :url, :views
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'homepage'

  def index
  end
end

app/controllers/videos_controller.rb
require 'open-uri'

class VideosController < ApplicationController
  def index
    @videos = Video.all
  end
  def new
  end
  def search
    search = params[:video]
    url = "http://youtube.com/results?search_query=#{search}"
    html = Nokogiri::HTML(open(url))
    lis = html.css('#search-results li')
    lis.each do |li|
      url = li.get_attribute('data-context-item-id')
      # views = li.get_attribute('data-context-item-views')
      title = li.get_attribute('data-context-item-title')
      Video.create(:title => title, :url => url)
    end

    redirect_to(videos_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="twelve columns">
    <hr />
    <div class="row">
      <div class="six columns">
        <p>&copy; Copyright no one at all. Go to town.</p>
      </div>
      <div class="six columns">
        <ul class="link-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="three columns">
    <h1><img src="http://placehold.it/400x100&text=Logo" /></h1>
  </div>
  <div class="nine columns">
    <ul class="nav-bar right">
      <li><%= link_to('Home', root_path) %></li>
      <li><%= link_to('Search', videos_new_path) %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <!-- <title>Welcome to Foundation | Homepage</title> -->
  <title>R20130215Foundation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed)
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">
  <script src="javascripts/modernizr.foundation.js"></script>
  -->
</head>
<body>
  <%= render :partial => 'layouts/nav' %>
  <div class='row'>
    <div class='twelve columns'><%= yield %></div>
  </div>
  <%= render :partial => 'layouts/footer' %>
  <script type="text/javascript">
     $(window).load(function() {
         $('#slider').orbit();
     });
  </script>
</body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <!-- <title>Welcome to Foundation | Homepage</title> -->
  <title>R20130215Foundation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed)
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/app.css">
  <script src="javascripts/modernizr.foundation.js"></script>
  -->
</head>
<body>

  <!-- Header and Nav -->

  <%= render :partial => 'layouts/nav' %>

  <!-- End Header and Nav -->


  <!-- First Band (Slider) -->
  <!-- The Orbit slider is initialized at the bottom of the page by calling .orbit() on #slider -->

  <div class="row">
    <div class="twelve columns">
      <div id="slider">
        <img src="http://placehold.it/1000x400&text=[img 1]" />
        <img src="http://placehold.it/1000x400&text=[img 2]" />
        <img src="http://placehold.it/1000x400&text=[img 3]" />
        <img src="http://placehold.it/1000x400&text=[img 4]" />
      </div>

      <hr />
    </div>
  </div>


  <!-- Three-up Content Blocks -->

  <div class="row">

    <div class="four columns">
      <img src="http://placehold.it/400x300&text=[img]" />
      <h4>This is a content section.</h4>
      <%= yield %>
      <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>

    <div class="four columns">
      <img src="http://placehold.it/400x300&text=[img]" />
      <h4>This is a content section.</h4>
      <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>

    <div class="four columns">
      <img src="http://placehold.it/400x300&text=[img]" />
      <h4>This is a content section.</h4>
      <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>

  </div>


  <!-- Call to Action Panel -->
  <div class="row">
    <div class="twelve columns">

      <div class="panel">
        <h4>Get in touch!</h4>

        <div class="row">
          <div class="nine columns">
            <p>We'd love to hear from you, you attractive person you.</p>
          </div>
          <div class="three columns">
            <a href="#" class="radius button right">Contact Us</a>
          </div>
        </div>
      </div>

    </div>
  </div>


  <!-- Footer -->

  <%= render :partial => 'layouts/footer' %>

  <!-- Included JS Files (Uncompressed) -->
  <!--

  <script src="javascripts/jquery.js"></script>

  <script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>

  <script src="javascripts/jquery.foundation.forms.js"></script>

  <script src="javascripts/jquery.event.move.js"></script>

  <script src="javascripts/jquery.event.swipe.js"></script>

  <script src="javascripts/jquery.foundation.reveal.js"></script>

  <script src="javascripts/jquery.foundation.orbit.js"></script>

  <script src="javascripts/jquery.foundation.navigation.js"></script>

  <script src="javascripts/jquery.foundation.buttons.js"></script>

  <script src="javascripts/jquery.foundation.tabs.js"></script>

  <script src="javascripts/jquery.foundation.tooltips.js"></script>

  <script src="javascripts/jquery.foundation.accordion.js"></script>

  <script src="javascripts/jquery.placeholder.js"></script>

  <script src="javascripts/jquery.foundation.alerts.js"></script>

  <script src="javascripts/jquery.foundation.topbar.js"></script>

  <script src="javascripts/jquery.foundation.joyride.js"></script>

  <script src="javascripts/jquery.foundation.clearing.js"></script>

  <script src="javascripts/jquery.foundation.magellan.js"></script>

  -->

  <!-- Included JS Files (Compressed)
  <script src="javascripts/jquery.js"></script>
  <script src="javascripts/foundation.min.js"></script>

  Initialize JS Plugins
  <script src="javascripts/app.js"></script>
  -->

  <script type="text/javascript">
     $(window).load(function() {
         $('#slider').orbit();
     });
  </script>

</body>
</html>

app/views/videos/_youtube.html.erb
<iframe width="560" height="315" src="http://www.youtube.com/embed/<%= url %>" frameborder="0" allowfullscreen></iframe>

app/views/videos/index.html.haml
%ul
  - @videos.each do |video|
    %li= render(:partial => 'youtube', :locals => {:url => video.url})

app/views/videos/new.html.haml
.row
  .four.columns
    = form_tag videos_new_path do
      = label_tag 'video'
      = text_field_tag 'video', nil, :autofocus => true
      = submit_tag 'Search Videos', :class => 'button radius'
  .eight.columns